name: ndis_connect
description: NDIS Connect – Accessible, role-based companion for NDIS participants and providers.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # =============================================================================
  # Core Flutter Dependencies
  # =============================================================================
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter

  # =============================================================================
  # State Management & Architecture
  # =============================================================================
  provider: ^6.1.2
  collection: ^1.19.1

  # =============================================================================
  # Firebase & Backend Services
  # =============================================================================
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_messaging: ^16.0.1
  firebase_analytics: ^12.0.1
  firebase_crashlytics: ^5.0.1

  # =============================================================================
  # Local Storage & Caching
  # =============================================================================
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0

  # =============================================================================
  # Security & Authentication
  # =============================================================================
  flutter_secure_storage: ^9.2.2
  cryptography: ^2.7.0
  local_auth: ^2.3.0
  crypto: ^3.0.5

  # =============================================================================
  # Network & Connectivity
  # =============================================================================
  http: ^1.2.2
  connectivity_plus: ^6.0.5
  cached_network_image: ^3.4.1

  # =============================================================================
  # UI & User Experience
  # =============================================================================
  # Charts and Data Visualization
  fl_chart: ^1.1.0
  
  # Animations and Effects
  lottie: ^3.1.2
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  confetti: ^0.8.0
  
  # Maps and Location
  google_maps_flutter: ^2.9.0
  geolocator: ^14.0.2

  # =============================================================================
  # Voice & Speech Features
  # =============================================================================
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.0

  # =============================================================================
  # AI & Machine Learning
  # =============================================================================
  google_ml_kit: ^0.20.0
  google_generative_ai: ^0.4.6

  # =============================================================================
  # Notifications & Background Tasks
  # =============================================================================
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.0
  workmanager: ^0.9.0+3
  permission_handler: ^12.0.1

  # =============================================================================
  # Document Generation & Printing
  # =============================================================================
  pdf: ^3.11.1
  printing: ^5.13.2

  # =============================================================================
  # Monetization
  # =============================================================================
  in_app_purchase: ^3.1.13

  # =============================================================================
  # Navigation
  # =============================================================================
  go_router: ^14.6.2
  
  # =============================================================================
  # Utilities
  # =============================================================================
  url_launcher: ^6.3.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # =============================================================================
  # Code Quality & Linting
  # =============================================================================
  flutter_lints: ^6.0.0
  
  # =============================================================================
  # Testing
  # =============================================================================
  mockito: ^5.4.4
  build_runner: ^2.4.13
  integration_test:
    sdk: flutter
  test: ^1.26.2
  bloc_test: ^10.0.0
  golden_toolkit: ^0.15.0
  network_image_mock: ^2.1.1
  fake_async: ^1.3.1
  clock: ^1.1.1
  
  # =============================================================================
  # Code Generation
  # =============================================================================
  hive_generator: ^2.0.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/