name: ndis_connect
description: NDIS Connect – Accessible, role-based companion for NDIS participants and providers.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.3
  url_launcher: ^6.3.0
  intl: ^0.20.2
  speech_to_text: ^7.0.0
  geolocator: ^14.0.2
  pdf: ^3.11.0
  printing: ^5.13.1
  confetti: ^0.8.0

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_messaging: ^16.0.1
  firebase_analytics: ^12.0.1
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1

  # Maps
  google_maps_flutter: ^2.7.0
  in_app_purchase: ^3.1.11
  local_auth: ^2.1.8

  # Security & crypto (for E2E encrypted notes/circles)
  flutter_secure_storage: ^9.2.4
  cryptography: ^2.5.0
  http: ^1.2.1
  
  # Error handling and crash reporting
  firebase_crashlytics: ^5.0.1

  # AI & ML Features
  google_ml_kit: ^0.20.0
  
  # Advanced Analytics & Visualization
  fl_chart: ^1.1.0
  syncfusion_flutter_charts: ^31.1.17
  syncfusion_flutter_gauges: ^31.1.17
  
  # Voice & Speech
  flutter_tts: ^4.2.3
  permission_handler: ^12.0.1
  
  # Advanced Caching & Performance
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  
  # Background Processing
  workmanager: ^0.9.0+3
  
  # Advanced UI Components
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_staggered_animations: ^1.1.1
  
  # Internationalization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/