// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApnZHdnV4GcI8sCFRIkjCD8idR0U1BgNg',
    appId: '1:573485849448:web:c5ac0d19f7c3fc2ebd94dd',
    messagingSenderId: '573485849448',
    projectId: 'ndis-connect-91f11',
    authDomain: 'ndis-connect-91f11.firebaseapp.com',
    storageBucket: 'ndis-connect-91f11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtNI1a4v1ZDdCglW5hNfTnKi59EKK2AYw',
    appId: '1:573485849448:android:3ed2dcb376be163dbd94dd',
    messagingSenderId: '573485849448',
    projectId: 'ndis-connect-91f11',
    storageBucket: 'ndis-connect-91f11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApnZHdnV4GcI8sCFRIkjCD8idR0U1BgNg',
    appId: '1:573485849448:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '573485849448',
    projectId: 'ndis-connect-91f11',
    storageBucket: 'ndis-connect-91f11.firebasestorage.app',
    iosBundleId: 'com.example.ndisConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApnZHdnV4GcI8sCFRIkjCD8idR0U1BgNg',
    appId: '1:573485849448:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '573485849448',
    projectId: 'ndis-connect-91f11',
    storageBucket: 'ndis-connect-91f11.firebasestorage.app',
    iosBundleId: 'com.example.ndisConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApnZHdnV4GcI8sCFRIkjCD8idR0U1BgNg',
    appId: '1:573485849448:web:c5ac0d19f7c3fc2ebd94dd',
    messagingSenderId: '573485849448',
    projectId: 'ndis-connect-91f11',
    authDomain: 'ndis-connect-91f11.firebaseapp.com',
    storageBucket: 'ndis-connect-91f11.firebasestorage.app',
  );
}
